//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampAssist
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccommodationUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccommodationUnit()
        {
            this.AccommodationUnitGuests = new HashSet<AccommodationUnitGuest>();
            this.Reservations = new HashSet<Reservation>();
            this.ReservationDates = new HashSet<ReservationDate>();
        }
    
        public int AccommodationUnitID { get; set; }
        public string Name { get; set; }
        public Nullable<double> PriceSeason { get; set; }
        public Nullable<double> PriceOffSeason { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<AccommodationUnitGuest> AccommodationUnitGuests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<ReservationDate> ReservationDates { get; set; }
    }
}
