//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampAssist
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationDate
    {
        public int ReservationDateID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> AccommodationUnitID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> ReservationID { get; set; }
    
        public virtual AccommodationUnit AccommodationUnit { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
